### ISSUE TITLE
JsonLdError [jsonld.ValidationError]: Safe mode validation error.

### ISSUE THREAD

**Issue by joelamouche** [iden3/js-jsonld-merklization#34]
I run 

````
import { Merklizer, Path } from "@iden3/js-jsonld-merklization";
const jsonLD = `{"@context":[{"@protected":true,"@version":1.1,"id":"@id","type":"@type","IDScan":{"@context":{"@propagate":true,"@protected":true,"polygon-vocab":"urn:uuid:58acdc49-1a7d-45ff-bf8d-67c55831453b#","xsd":"http://www.w3.org/2001/XMLSchema#","highLevelResult":{"@id":"polygon-vocab:highLevelResult","@type":"xsd:string"},"journeyId":{"@id":"polygon-vocab:journeyId","@type":"xsd:string"},"firstName":{"@id":"polygon-vocab:firstName","@type":"xsd:string"},"middleName":{"@id":"polygon-vocab:middleName","@type":"xsd:string"},"lastName":{"@id":"polygon-vocab:lastName","@type":"xsd:string"},"gender":{"@id":"polygon-vocab:gender","@type":"xsd:string"},"age":{"@id":"polygon-vocab:age","@type":"xsd:integer"},"citizenship":{"@id":"polygon-vocab:citizenship","@type":"xsd:string"},"documentCategory":{"@id":"polygon-vocab:documentCategory","@type":"xsd:string"},"documentName":{"@id":"polygon-vocab:documentName","@type":"xsd:string"},"documentSide":{"@id":"polygon-vocab:documentSide","@type":"xsd:string"},"documentType":{"@id":"polygon-vocab:documentType","@type":"xsd:string"},"entryDate":{"@id":"polygon-vocab:entryDate","@type":"xsd:string"},"entryTime":{"@id":"polygon-vocab:entryTime","@type":"xsd:string"},"fullName":{"@id":"polygon-vocab:fullName","@type":"xsd:string"},"addressLine1":{"@id":"polygon-vocab:addressLine1","@type":"xsd:string"},"addressLine2":{"@id":"polygon-vocab:addressLine2","@type":"xsd:string"},"birthDate":{"@id":"polygon-vocab:birthDate","@type":"xsd:string"},"birthPlace":{"@id":"polygon-vocab:birthPlace","@type":"xsd:string"},"faceMatchScore":{"@id":"polygon-vocab:faceMatchScore","@type":"xsd:string"},"qualityCheckDetails":{"@id":"polygon-vocab:qualityCheckDetails","@context":{"id":{"@id":"polygon-vocab:qualityCheckDetails.id","@type":"xsd:string"},"title":{"@id":"polygon-vocab:qualityCheckDetails.title","@type":"xsd:string"},"description":{"@id":"polygon-vocab:qualityCheckDetails.description","@type":"xsd:string"},"state":{"@id":"polygon-vocab:qualityCheckDetails.state","@type":"xsd:integer"}}},"validationDetails":{"@id":"polygon-vocab:validationDetails","@context":{"name":{"@id":"polygon-vocab:validationDetails.name","@type":"xsd:string"},"description":{"@id":"polygon-vocab:validationDetails.description","@type":"xsd:string"},"result":{"@id":"polygon-vocab:validationDetails.result","@type":"xsd:integer"}}},"highLevelResultDetails":{"@context":{"documentOverallValidation":{"@id":"polygon-vocab:documentOverallValidation","@type":"xsd:string"},"documentBlockingPolicy":{"@id":"polygon-vocab:documentBlockingPolicy","@type":"xsd:string"},"documentExpiry":{"@id":"polygon-vocab:documentExpiry","@type":"xsd:string"},"documentSupport":{"@id":"polygon-vocab:documentSupport","@type":"xsd:string"},"documentValidation":{"@id":"polygon-vocab:documentValidation","@type":"xsd:string"},"faceMatchValidation":{"@id":"polygon-vocab:faceMatchValidation","@type":"xsd:string"},"accumulativeLivenessResult":{"@id":"polygon-vocab:accumulativeLivenessResult","@type":"xsd:string"}},"@id":"polygon-vocab:highLevelResultDetails"}},"@id":"urn:uuid:362d5804-a195-4549-b15b-edb5ef50d203"}}]}`;
const mz = await Merklizer.merklizeJSONLD(jsonLD);
````

and I get this error:

````
JsonLdError [jsonld.ValidationError]: Safe mode validation error.
    at safeEventHandler (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/events.js:133:11)
    at _handle (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/events.js:82:7)
    at api.handleEvent (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/events.js:71:3)
    at _dropUnsafeObject (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/expand.js:421:7)
    at api.expand (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/expand.js:381:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.jsonld.expand (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/jsonld.js:321:18)
    at async Function.jsonld.toRDF (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/jsonld.js:680:16)
    at async jsonld.normalize.jsonld.canonize (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/jsonld@8.2.1/node_modules/jsonld/lib/jsonld.js:585:19)
    at async Function.fromDocument (/Users/antoineestienne/Github_Files/NexeraID/node_modules/.pnpm/@iden3+js-jsonld-merklization@1.0.2/node_modules/@iden3/js-jsonld-merklization/src/lib/rdf-dataset.ts:35:28) {
  details: {
    event: {
      type: [Array],
      code: 'empty object',
      level: 'warning',
      message: 'Dropping empty object.',
      details: [Object]
    }
  }
}
````

**Comment by vmidyllic** [comment]
discussed externally, schema was incorrect.
